name: utf_ext
description: A library for reading / writing text files in any major Unicode format (UTF-8,16LE,16BE,32LE,32BE)
version: 0.1.0
homepage: https://aiurovet.blogspot.com/
repository: https://github.com/aiurovet/utf_ext/

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  async: ^2.10.0
  file: ^6.1.4
  loop_visitor: ^0.3.0

dev_dependencies:
  file_ext: ^0.3.1
  lints: ^2.0.0
  parse_args: ^0.12.1
  thin_logger: ^0.2.0
  test: ^1.16.0
