name: utf_ext
description: A library for reading and writing text files in any major Unicode format (UTF-8, UTF-16LE, UTF-16BE, UTF-32LE, UTF-32BE)
version: 0.3.1
homepage: https://aiurovet.com/
repository: https://github.com/aiurovet/utf_ext/

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  async: ^2.11.0
  file: ^7.0.0
  loop_visitor: ^0.4.0

dev_dependencies:
  file_ext: ^0.7.3
  lints: ^3.0.0
  parse_args: ^0.13.2
  thin_logger: ^0.2.2
  test: ^1.23.1
